services:
  redmine:
    image: redmine:5
    container_name: redmine
    restart: always
    ports:
      - "3000:3000"
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
      REDMINE_DB_ENCODING: utf8mb4
    volumes:
      - c:/data/redmine/files:/usr/src/redmine/files
      - c:/data/redmine/plugins:/usr/src/redmine/plugins
      - c:/data/redmine/themes:/usr/src/redmine/public/themes
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: redmine-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine
      TZ: Asia/Seoul
    volumes:
      - c:/data/mysql:/var/lib/mysql
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
