services:
  app1:
    build: ./app1
    image: cyannara/app1:latest
    container_name: app1-container
    ports:
      - "8081:8080"
    environment:
      - TZ=Asia/Seoul

  app2:
    build: ./app2
    image: cyannara/app2:latest
    container_name: app2-container
    ports:
      - "8082:8080"
    environment:
      - TZ=Asia/Seoul
